Repository Dragontalker/FrontEnd-EasyRedditTrackerForCrypto, pull requests merged in 2021-02, with the labels that each got.

#2 index
  index.html
Labels: bug

#19 Reddit demo richard
  demoAPI/redditAPI/reddit.css
  demoAPI/redditAPI/reddit.html
  demoAPI/redditAPI/reddit.js
Labels: enhancement

#21 Added files needed to create a demo for crypto API.
  demoAPI/crytoAPI/crypto.css
  demoAPI/crytoAPI/crypto.js
  demoAPI/crytoAPI/cryto.html
Labels: enhancement

#25 Merge develop back into main to reduce confusion
  demoAPI/crytoAPI/crypto.css
  demoAPI/crytoAPI/crypto.js
  demoAPI/crytoAPI/cryto.html
  demoAPI/redditAPI/reddit.css
  demoAPI/redditAPI/reddit.html
  demoAPI/redditAPI/reddit.js
  login.html
Labels: enhancement

#28 Added a dropdown menu for quantity limit on search items.
  demoAPI/redditAPI/reddit.html
Labels: enhancement

#31 Reddit API demo with search function
  demoAPI/redditAPI/reddit.html
  demoAPI/redditAPI/reddit.js
  reddit-api.js
Labels: enhancement

#34 Addressing Issue#33
  login.html
Labels: enhancement

#38 Created a displaying page for results fetched from Reddit API.
  Assets/CSS/style.css
  Assets/JavaScript/script.js
  redditResults.html
Labels: enhancement

#42 Fixed the difference in style.css.
  Assets/CSS/style.css
Labels: conflict

#43 Resolved the conflicts between shiva's branch and main branch on style.css
  Assets/CSS/style.css
Labels: conflict

#46 Fixed Issue#45.
  Assets/JavaScript/script.js
Labels: conflict

#48 Fixed Issue#47.
  login.html
Labels: conflict

#49 Crypto API Demo from Giovanni
  demoAPI/crytoAPI/crypto.css
  demoAPI/crytoAPI/crypto.js
  demoAPI/crytoAPI/cryto.html
Labels: feature request

#51 Updating Shiva's login files
  demoAPI/shivaDemo/shiva/Reddit.html
  demoAPI/shivaDemo/shiva/asset/bitcoin.webp
  demoAPI/shivaDemo/shiva/generalScript.js
  demoAPI/shivaDemo/shiva/generalStyle.css
  demoAPI/shivaDemo/shiva/login.html
Labels: duplicate

#58 Fixed all the inproper display issue.
  demoAPI/cryptoAPI/crypto.css
  demoAPI/cryptoAPI/crypto.html
  demoAPI/cryptoAPI/crypto.js
Labels: feature request, invalid

#61 Added a simple format example for local storage strategy.
  Back-end-development/localStorageFormat/storageFormat.js
Labels: feature request

#66 Added a simple format example for local storage strategy. (#61)
  Back-end-development/localStorageFormat/storageFormat.js
Labels: feature request
